### ISSUE TITLE
Error: No method in multimethod 'datatype-expansion.canonical-form/canonical-form' for dispatch value: $recur

### ISSUE THREAD

**Issue by ryan-slack-big** [raml-org/ramldt2jsonschema#12]
Is this a defect in dt2js or the RAML?
 
text.raml: 
```
#%RAML 1.0
title: My API With Types
types:
  Person:
    type: object
    properties:
      name: string
  Employee:
    type: Person
    properties:
      id: string
      spouse: Person
````
> $ dt2js test.raml Employee
> [Error: No method in multimethod 'datatype-expansion.canonical-form/canonical-form' for dispatch value: $recur]
