### ISSUE TITLE
Doesnt handle simple RAML 1 example from site

### ISSUE THREAD

**Issue by kevinduffey** [raml-org/ramldt2jsonschema#13]
This is probably already known, but the simple example of RAML 1 data types is not supported for the most part. This is a MUCH needed tool so I hope someone gets on to fixing this ASAP to fully support RAML 1.0 DataTypes. The below pasted example from the RAML 1 example documentation... if you try to convert Group-new, or Group-update, it works. But Group fails.

As well, there needs to be more example RAML 1.0 types that work completely, and as issues are fixed/features added, update the RAML 1.0 type examples that will work. Things like inheritance, includes, custom types, enumerations, etc should all have good examples to show what works with this tool.

```
  Group-base:
    usage: The base type for group records
    properties:
      name:
        required: true

  Group-new:
    usage: Data for creating a new group
    type: Group-base
    properties:
      ITAuth:
        description: Authorization received from IT
        required: true

  Group-update:
    usage: Changeable properties of an existing group
    properties:
      name:

  Group:
    usage: A group in the system
    type: [ Group-base, Record-base ]
    properties:
      groupnum:
        type: StaticGroupNums | DynamicGroupNum
        required: true
```
