### ISSUE TITLE
JsonSchema -> RAML incorrect

### ISSUE THREAD

**Issue by andyws** [raml-org/ramldt2jsonschema#14]
Docs state: 

> Limitations
> in js2dt,
> 
> the following JSON schema properties are not supported and as a result, will not be converted:
> format, title, not

However the following jsonschema generates the below raml including the not supported "title", "format" etal

```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Basis period",
  "type": "object",
  "properties": {
    "start": {
      "title": "Start date",
      "description": "Date your basis period began",
      "type": "string",
      "format": "date"
    },
    "end": {
      "title": "End date",
      "description": "Date your basis period ended",
      "type": "string",
      "format": "date"
    }
  },
  "required": [
    "start",
    "end"
  ],
  "additionalProperties": false
}

```
```
#%RAML 1.0 Library

types:
  BasisPeriod:
    title: Basis period
    type: object
    properties:
      start:
        title: Start date
        description: Date your basis period began
        type: string
        format: date
        required: true
      end:
        title: End date
        description: Date your basis period ended
        type: string
        format: date
        required: true
    additionalProperties: false

```
