### ISSUE TITLE
type conversation is broken for integer & boolean : v0.1.2

### ISSUE THREAD

**Issue by TTRh** [raml-org/ramldt2jsonschema#31]
See this example : 

```
types:
    Foo:
        type: object
        additionalProperties: false
        properties:
          key1:
            type: integer
            default: 1
          key2:
            type: string
            required: false
          key3:
            type: boolean
            default: true
```

I get 
```
{
  "type": "object",
  "additionalProperties": "false",
  "properties": {
    "key1": {
      "type": "integer",
      "default": "1"
    },
    "key2": {
      "type": "string"
    },
    "key3": {
      "type": "boolean",
      "default": "true"
    }
  },
  "required": [
    "key1",
    "key2",
    "key3"
  ],
  "$schema": "http://json-schema.org/draft-04/schema#"
}
```

boolean is not converted properly so additionalProperties not working, required property not working
integer either so default values not working
