### ISSUE TITLE
type conversion is broken with v0.1.3

### ISSUE THREAD

**Issue by TTRh** [raml-org/ramldt2jsonschema#42]
See this example:
```
types:
    SearchQuery:
        type: object
        additionalProperties: false
        properties:
          from:
            type: integer
            default: 0
            minimum: 0
            maximum: 10
          partial:
            type: string
            enum: ["true", "false"]
            default: "true"
```
I get : 

```
{
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "from": {
      "type": "integer",
      "default": "0",
      "minimum": "0",
      "maximum": 10
    },
    "partial": {
      "type": "string",
      "enum": [
        "true",
        "false"
      ],
      "default": true
    }
  },
  "required": [],
  "$schema": "http://json-schema.org/draft-04/schema#"
}
```

* the minimum/default attribute get's string, but should be integer (as the maximum attribute is btw)
* for the partial attribute, I defined it as enum `{"false", "true"}` (as string not boolean) and the default value get's cast as boolean.

**Comment by jstoiko** [comment]
@TTRh: can you look at and try the proposed fix and let us know if it takes care of your issue?

**Comment by TTRh** [comment]
#44 fix partially this issue: it also introduce a regression, see : 

```
types:
    TimeRange:
      type: string
      enum:
        - "1"
        - "3"
        - "7"
        - "30"

    SearchQuery:
        type: object
        additionalProperties: false
        properties:
          from:
            type: integer
            default: 0
            minimum: 0
            maximum: 10
          partial:
            type: string
            enum: ["true", "false"]
            default: "true"
          time_range:
            type: TimeRange
            default: "1"
```

I get now
```
{
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "from": {
      "type": "integer",
      "default": 0,
      "minimum": 0,
      "maximum": 10
    },
    "partial": {
      "type": "string",
      "enum": [
        "true",
        "false"
      ],
      "default": "true"
    },
    "time_range": {
      "type": "string",
      "enum": [
        "1",
        "3",
        "7",
        "30"
      ],
      "default": 1
    }
  },
  "required": [
    "from",
    "partial",
    "time_range"
  ],
  "$schema": "http://json-schema.org/draft-04/schema#"
}
```

**Comment by TTRh** [comment]
More details about the regression type conversation is now broken for all properties which have a custom type. See: 

```
types:

  TimeRange:
    type: string
    enum:
      - "1"
      - "3"
      - "7"
      - "30"

  Toggle:
    type: string
    enum:
      - "false"
      - "true"

  SearchQuery:
      type: object
      additionalProperties: false
      properties:
        from:
          type: integer
          default: 0
          minimum: 0
          maximum: 10
        partial:
          type: Toggle
          default: "true"
        time_range:
          type: TimeRange
          default: "1"
```

and I get : 
```
{
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "from": {
      "type": "integer",
      "default": 0,
      "minimum": 0,
      "maximum": 10
    },
    "partial": {
      "type": "string",
      "enum": [
        "false",
        "true"
      ],
      "default": true
    },
    "time_range": {
      "type": "string",
      "enum": [
        "1",
        "3",
        "7",
        "30"
      ],
      "default": 1
    }
  },
  "required": [
    "from",
    "partial",
    "time_range"
  ],
  "$schema": "http://json-schema.org/draft-04/schema#"
}
```
