### ISSUE TITLE
Duplicate entry `items` in required array v0.1.3

### ISSUE THREAD

**Issue by TTRh** [raml-org/ramldt2jsonschema#43]
Here is an example : 

```
types:
  Foo:
    type: object
    properties:
      items: integer[]
      total_count: integer
```
I get

```
 {
  "type": "object",
  "properties": {
    "items": {
      "type": "array",
      "items": {
        "type": "integer"
      }
    },
    "total_count": {
      "type": "integer"
    }
  },
  "additionalProperties": true,
  "required": [
    "items",
    "items",
    "total_count"
  ],
  "$schema": "http://json-schema.org/draft-04/schema#"
}
```

Seems that's a very special case where I have `items` as object property
