### ISSUE TITLE
Wrong required with object and examples

### ISSUE THREAD

**Issue by darkrodry** [raml-org/ramldt2jsonschema#65]
Hi there!

I've found an error trying to parse an object with object properties and an example.

For example, I have a RAML library like:
```
#%RAML 1.0 Library

types:
  randomObject:
    type: object
    example: !include someExample.json
    properties:
      foo: 
        type: object
        required: false
        properties:
          bar: string
```
And 'someExample.json' like:
```
{
  "foo": {
    "bar": "lorem ipsum"
  }
}
```
So I expect to have a json schema with an empty required array for randomObject, but I get the following:
```
{
  "type": "object",
  "example": {
    "foo": {
      "bar": "lorem ipsum"
    }
  },
  "properties": {
    "foo": {
      "type": "object",
      "properties": {
        "bar": {
          "type": "string"
        }
      },
      "additionalProperties": true,
      "required": [
        "bar"
      ]
    }
  },
  "additionalProperties": true,
  "required": [
    "foo"
  ],
  "$schema": "http://json-schema.org/draft-06/schema#"
}
```
If I remove the example in the RAML file, I get the expected json schema output:
```
{
  "type": "object",
  "example": {},
  "properties": {
    "foo": {
      "type": "object",
      "properties": {
        "bar": {
          "type": "string"
        }
      },
      "additionalProperties": true,
      "required": [
        "bar"
      ]
    }
  },
  "additionalProperties": true,
  "$schema": "http://json-schema.org/draft-06/schema#"
}
```
I'm working in a fix for this problem right now. As I saw, the dt2js.js file parse the example facet using the same steps as the properties facet, expecting the required facet, so we need to check if this facet exist in the data to parse because datatype-expansion library set it to true if it is not defined inside the RAML file.
